README.md, assets/js/components/search.vue, config.yml, content/about/_index.md, content/blog/contributing-to-rivet.md, content/blog/integrating-rivet.md, content/blog/open-sourcing-rivet.md, content/blog/release-0.5.0.md, content/blog/release-1-1-0.md, content/blog/release-1.0.0.md, content/blog/rivet-add-ons.md, content/blog/rivet-in-2019.md, content/components/_index.md, content/components/information/contributing.md
This PR updates old links to github.iu where appropriate. Some of them link to old archived PRs so will need to remain. And the changelog URL will need to stay in place until we move the release notes over.
=> Updated old URLs

content/blog/panel-deprecation.md
Can't believe I missed the missing `.` and double "they."
=> Backmerge blog post hotfix

content/about/_index.md
The link on the _About_ page was still pointing to the old fragment on the home page. This PR fixes that link so it goes to the new dedicated roadmap page.
=> Fixed link to roadmap

content/components/layout/typography.md, data/tokens.json, layouts/shortcodes/typescale.html
This PR adds documentation for Rivet's typography Sass variables.
We use Sass to generate all of the type scale utility CSS classes used in Rivet. We make those same sass variables available in the main Rivet package (ZIP file and npm). We haven't really done a great job of documenting how to use those folks using Rivet's Sass files in their own projects. This PR is a first crack at documenting how to use the Sass files.
There's nothing fancy or groundbreaking here, but if we decide this format is effective, we can carry it through on the docs for [spacing](https://rivet.iu.edu/components/layout/spacing/), [z-index](https://rivet.iu.edu/components/utilities/z-index/), [breakpoints](https://github.com/indiana-university/rivet-source/blob/develop/src/sass/core/_variables.scss#L334), and …
=> Adds documentation for typography Sass variables

config.yml, content/blog/release-1-3-0.md, content/components/_index.md, content/components/layout/spacing.md, content/components/utilities/flex.md, package-lock.json, package.json, static/changelog.json
This PR adds docs for new spacing and flex utilities. I'll leave this open so we can get the `1.3.0` blog post added before we merge into develop for testing/review.
Once the final `rivet-uits@1.3.0` release is available we can launch the updates.
=> Made initial 1.3.0 docs updates

assets/scss/_shame.scss, assets/scss/components/_rvtd-layout.scss, layouts/changelog/single.html, layouts/partials/head.html, layouts/partials/scripts.html, layouts/partials/search-form.html, layouts/partials/section-nav.html, layouts/partials/sidebar.html, layouts/status/single.html
This PR adds the Algolia docSearch service to the Rivet documentation site. You can read more about docSearch here:
https://community.algolia.com/docsearch/
This service is only available on the main rivet.iu.edu domain, so this PR will need to be merged into master instead of develop.
=> Added docSearch service 

content/components/forms/buttons-segmented.md, content/components/forms/buttons.md, content/components/forms/input-group.md, content/components/information/contributing.md, content/components/navigation/dropdown.md, content/components/navigation/header.md, content/components/overlays/alerts.md, content/components/overlays/modals.md, content/components/page-content/media-object.md, layouts/add-ons/single.html, layouts/changelog/single.html, layouts/partials/drawer-button.html, layouts/partials/drawer.html, layouts/partials/header.html, layouts/partials/support-form.html, layouts/shortcodes/code.html, layouts/shortcodes/example.html, layouts/status/single.html
This PR addresses issue #35. It adds `type="button"` to buttons which are not intended to be (or demonstrate) submittable buttons. 
@scottanthonymurray I could especially use your feedback on the language for the alert on `buttons.md: line 26`.
=> Added type property to non-submittable buttons and created alert

layouts/partials/scripts.html
This PR fixes the console errors we were seeing on pages where the search input doesn't appear.
I've updated the script so that it check to see if the input exists before continuing with initializing the `docsearch` script.
=> Fixed console errors on pages without docsearch input

layouts/partials/footer.html, layouts/partials/support-form.html
This PR adds `target="_blank" rel="noopener` where appropriate to open external links in new tabs in the footer and support popup.
=> Updated footer and support widget external links to open in tab

.gitignore
Updated `.gitignore` file to include newly standardized items such as .env files, debug logs, etc. See issue #39.
=> Added standard items to the .gitignore file

config.yml, content/components/_index.md, content/components/overlays/alerts.md, content/components/overlays/loading-indicator.md, content/components/utilities/display.md, data/changelog.json, data/tokens.json, package-lock.json, package.json
This PR makes documentation updates to reflect the changes in Rivet 1.4.0.
@illusivesunrae @scottanthonymurray I'm getting this PR open for the 1.4.0 updates to the docs site. 
Trying out something new here with GitHub markdown [task lists](https://help.github.com/en/articles/about-task-lists) (see above). If you're working on any of these to-do feel free to check them off as you push commits that address any item on the list.
=> Made updates to reflect changes for 1.4.0 release

content/blog/release-1-4-0.md
This PR adds a blog post announcing the release of Rivet `1.4.0`.
=> Added 1.4.0 release blog post

layouts/partials/notifications-menu.html
Updating to Hugo `0.55` caused the date formatter function call in the notifications menu partial to see `.Params.date` as null and throw an error.
=> Fixed dateFormat syntax to work in Hugo 0.55

content/components/utilities/display.md, content/components/utilities/visibility.md
Fixes #84.
This PR also moves the documentation about `.rvt-sr-only` from the Display docs to the Visibility docs, per issue request.
=> Added link to UXO doc on accessible content hiding to .rvt-sr-only docs

layouts/shortcodes/a11y.html
Hotfix, will backmerge into `develop`
=> Added missing markdownify function call to a11y shortcode

package.json
This PR backmerges the hotfix made to `master` #111 to add the missing `markdownify` function call to the a11y shortcode
=> Backmerge a11y shortcode hotfix

assets/scss/_shame.scss
A `z-index` of 100 was chosen because it's less than 1000 (the drawer `z-index`) and matches the `z-index` of other elements of the Algolia box.
Fixes #109
=> Updated Algolia search box z-index to prevent it from overlapping drawer on mobile

assets/scss/_shame.scss, assets/scss/components/_rvtd-layout.scss, layouts/partials/footer.html
Fixed .rvtd-wrap issue, and added targeted css for docs site footer to prevent bunching of text. This addresses issue #108.
=> Fixed IE11 footer display issue

content/components/forms/buttons.md
This PR updates the instructions regarding the use of icons within buttons to clarify that icons should appear before any text unless standard conventions are to appear after (such as for a dropdown menu).
See issue #56 for more details.
=> Updated instructions for using icons inside buttons

content/components/utilities/visibility.md
This PR fixes a typo within `visibility.md` where 'hide' is spelled 'ide'.
=> Fixed 'hide' typo

content/components/_index.md, content/components/navigation/header.md, layouts/partials/trident.html
The `aria-describedby` on the `svg` element was removed across multiple files with trident code examples.
See the issue indiana-university/rivet-source/issues/200 for more details.
=> Removed aria-describedby from trident svg

assets/scss/_shame.scss, gulpfile.js
The `public` folder was not being regenerated during the build process (both dev and prod). Configured the `hugoProd` function to run at the end of the build process, and configured the `hugoDev` function to run when updates are made to `.js` and `.scss` files during the `watch` process.
See issue #147 for more details.
=> Fixed public folder generation issues

gulpfile.js
When fixing the previous `public` folder related issue (#147), I forgot to take into account the way the Bamboo plan works. I have removed the `hugoProd` piece from the Gulp build task, and it now runs correctly.
=> Removed hugoProd command from gulp build task

content/blog/rivet-1-end-of-life-plan.md
This PR adds a new blog post with info about the eventual _retirement_ of Rivet 1.x.x and the launch of Rivet 2.
=> Added new eol blog post

content/components/navigation/header.md, layouts/partials/header.html, layouts/partials/support-form.html
This PR removes the incorrect `role="menu"` attributes from both the header example code and the site header itself.
Can confirm that WAVE no longer throws a broken menu warning on the header and examples page.
Fixes #183
=> Removed role="menu" from header examples and instance
