- content/components/layout/box.md
Coming back to the box component documentation with fresh eyes as a user (I'm using the box component as part of the V261 final project), I noticed some improvements that I could make.
> Box docs clarifications

- content/about/_index.md
- content/blog/rivet-in-2019.md
- content/components/forms/text-input.md
- content/components/layout/grid.md
- content/components/layout/spacing.md
- content/components/layout/typography.md
- content/components/overlays/alerts.md
- data/tokens.json
- layouts/shortcodes/breakpoints.html
- layouts/shortcodes/spacing.html
- layouts/shortcodes/typescale.html
This PR adds documentation for the spacing and breakpoint Sass variables. It also makes a number of small updates to some broken links and other documentation.
Once this approved I'll get it merged and up on test for one last quick review and then we can deploy the updates to the live site in a separate PR.
> Added more documentation for Sass variable and breakpoints

- layouts/workshop/list.html
Reopening this to use for any additional edits.
> Makes updates to community workshop page

- layouts/workshop/list.html
tutorial-track -> coding-track
> Fixed incorrect duplicated section ID

- content/workshop/_index.md
- layouts/workshop/list.html
Also colorized and corrected singular/plural tense of lesson seats left
> Implemented disabled registration button on 0 spots left

- content/workshop/_index.md
- layouts/workshop/list.html
Disables registration button on 0 seats left, colorizes and corrects singular/plural seats left indicators for tutorial track lessons.
> Updated logic on workshop page for showing seats left

- content/blog/dcdi-announcement-takeaways.md
I'll leave this branch open after merging to add edits.
> Drafted DCD&I announcement blog post

- content/blog/dcdi-announcement-takeaways.md
Both Austin and Brian have reviewed the post, as has the Rivet team.
> Published blog post about DCDI announcement

- assets/scss/_shame.scss
- assets/scss/components/_rvtd-layout.scss
- layouts/changelog/single.html
- layouts/partials/head.html
- layouts/partials/scripts.html
- layouts/partials/search-form.html
- layouts/partials/section-nav.html
- layouts/partials/sidebar.html
- layouts/status/single.html
This PR adds DocSearch for real this time :) I discovered that the order in which the docsearch script was included in the page was causing it not to work. It must be the last script included in the page.
I can confirm everything is working locally and should be able to be tested from the staging site.
> Adds docsearch to replace home-grown search functionality

- content/components/_index.md
See https://rivet.iu.edu/components/navigation/footer/
> Updates Rivet starter template to use new branded footer released in 1.4.0

- content/components/_index.md
See https://rivet.iu.edu/components/navigation/footer/
> Updated Rivet starter template to use new branded footer released in 1.4.0

- assets/scss/_shame.scss
- content/blog/q1-2019-review.md
- layouts/shortcodes/blog-media-object.html
This PR also adds a shortcode for using media objects in blog posts to call out links to related media - in this case, a Kaltura video and a Google slide deck.
> Added blog post summarizing the Q1 2019 quarterly report

- content/components/getting-started/sass.md
- content/components/utilities/width.md
- data/tokens.json
- layouts/shortcodes/sassdocs.html
- layouts/shortcodes/widths.html
This PR adds documentation for the [newly-added responsive width utility classes](https://github.com/indiana-university/rivet-source/pull/107).
> Added documentation for responsive width utilities

- assets/scss/_shame.scss
- content/blog/spring-2019-workshop-slides.md
- layouts/shortcodes/blog-media-object.html
Opening this PR against `master` as there's changes in `develop` that shouldn't be live yet.
Will backmerge into `develop` on approval.
> Added blog post linking to spring 2019 workshop slides

- content/add-ons/rivet-shell.md
This PR updated she documentation for the shell add-on based on the new `1.0.0` version.
@scottanthonymurray the content could probably use a review when you get a chance, as I've rewritten some of it.
> Updated shell add-on docs to reflect recent updates

- content/components/page-content/badges.md
Trivial copy fix to correct a diction error.
> fix diction: visual "cues", not visual "queues"

- config.yml
- content/components/_index.md
- content/components/getting-started/npm.md
- data/changelog.json
- package-lock.json
- package.json
This PR finishes update to the docs ahead of the 1.6.0 release. Once to-do list is complete we can merge and publish the site.
> 1.6.0 Updates

- content/blog/why-we-built-rivet.md
> Updated Contribute button in Why We Built Rivet blog post to point to new wiki

- assets/scss/_shame.scss
- assets/scss/components/_rvtd-footer.scss
- layouts/partials/footer.html
In this PR:
- Updates the footer to reflect the new Rivet footer structure
- Adds small css fixes to handle bugs
@levimcg If you wouldn't mind taking a look at this, I had to add some additional css to get the footer to behave, which makes me think that we may need to review the current Rivet footer behavior on smaller screens.
See issue #119 for more details.
> Updated footer and added small css fixes

- content/blog/dcdi-announcement-takeaways.md
- content/blog/q1-2019-review.md
- content/blog/release-1.0.0.md
- content/blog/rivet-add-ons.md
- content/components/forms/file-input.md
- content/components/forms/input-group.md
- content/components/information/component-status.md
- content/components/navigation/dropdown.md
- content/components/overlays/alerts.md
- content/components/overlays/modals.md
- content/components/utilities/text.md
- content/content-guide/style-basics/punctuation.md
- content/jobs/front-end-developer.md
- layouts/partials/email-callout-sidebar.html
- layouts/workshop/list.html
This PR is meant to address remaining spelling errors on Rivet documentation site, per issue #78.
> Fixed spelling errors

- content/components/page-content/timeline.md
Note: Examples will appear broken until the next Rivet package is published and incorporated into the rivet-docs site.
> Added documentation for timeline component

- assets/scss/_shame.scss
- assets/scss/components/_rvtd-footer.scss
- config.yml
- content/blog/_index.md
- content/blog/dcdi-announcement-takeaways.md
- content/blog/q1-2019-review.md
- content/blog/release-1-7-0.md
- content/blog/release-1.0.0.md
- content/blog/rivet-add-ons.md
- content/components/_index.md
- content/components/forms/buttons.md
- content/components/forms/file-input.md
- content/components/forms/input-group.md
- content/components/getting-started/npm.md
- content/components/information/component-status.md
- content/components/navigation/dropdown.md
- content/components/overlays/alerts.md
- content/components/overlays/modals.md
- content/components/page-content/timeline.md
- content/components/utilities/text.md
- content/content-guide/style-basics/punctuation.md
- content/jobs/front-end-developer.md
- data/changelog.json
- layouts/partials/email-callout-sidebar.html
- layouts/partials/footer.html
- layouts/partials/notifications-menu.html
- layouts/shortcodes/example.html
- layouts/workshop/list.html
- package-lock.json
- package.json
This PR finishes update to the docs ahead of the 1.7.0 rivet-source release. Once to-do list is complete we can merge and publish the site.
> Rivet-source 1.7.0 release update

- content/components/layout/typography.md
- layouts/shortcodes/typescale.html
In this PR:
- Replaced `Fulfilling the promise` with `Lorem ipsum dolor sit`
> Removed fulfilling the promise

- layouts/partials/about-page/should-i-use.html
- layouts/partials/home-page/home-page-banner.html
- layouts/partials/should-i-use.html
This PR updates the text "CAS authentication" to "IU Login authentication" throughout the Docs site.
For more details, see issue #122.
> Updated the text CAS to IU Login

- assets/scss/_shame.scss
- layouts/index.html
- layouts/partials/home-page/home-page-2.0-announcement.html
This PR adds a banner to the home page that links to the 2.0 blog post announcement.
> Added 2.0 banner announcement to home page

- assets/scss/_shame.scss
- gulpfile.js
- layouts/partials/home-page/home-page-2.0-announcement.html
Update homepage announcement to point to v2.rivet.iu.edu
> Update homepage announcement

- layouts/partials/home-page/home-page-2.0-announcement.html
This PR makes the new EOL post live.
> Launches new Rivet 1.x.x eol blog post

- content/blog/resuming-rivet-2.md
- layouts/blog/single.html
- layouts/partials/toc.html
Also fixed blog template so blog posts can display without a Table of Contents
> Added new blog post about resuming Rivet development

- assets/js/plugins.js
- assets/js/rivet-docs.js
- layouts/partials/footer.html
> Updated copyright year to be dynamic

- layouts/partials/article-sidebar.html
Updated the sidebar text to remove link.
> Updated sidebar text

- content/blog/rivet-spea.md
Will be sending the Sitehost Test link to Mark after merging this PR. Any additional revisions will be made on this branch and a new PR will be opened.
> Added first draft of SPEA Rivet class blog post

- content/components/_index.md
Fixes https://app.asana.com/0/1199916208157344/1200856538628571/f
> Removed Axure kit notes from components page

- content/blog/_index.md
- layouts/blog/list.json
- static/.htaccess
This PR creates a JSON endpoint to fetch information about the 10 most recent blog posts.
`/blog/index.json`
This endpoint will be used to show a feed of recent blog posts on v2.rivet.iu.edu.
> Added JSON output for blog posts

- content/blog/release-beta-3.md
Getting this ready for the release tomorrow. We can push any further updates to this branch before pushing it live.
> Beta 3 blog post
